version: '3.8'
services:
  # api:
  #   container_name: api
  #   build: .
  #   tty: true
  #   ports:
  #     - '3000:3000'
  #   volumes:
  #     - type: bind
  #       source: .
  #       target: /api
  mysql:
    image: mysql/mysql-server:5.7
    command: --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
    ports:
      - '3306:3306'
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: develop
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    volumes:
      - /var/lib/mysql
